In [1]:
import tensorflow as tf

In [8]:
#Constant nodes
#When and how to use them
#Sessions

const_1 = tf.constant(value=[[1.0, 2.0]],
                     dtype=tf.float32,
                     shape=(1, 2),
                     name='const_1',
                     verify_shape=True)

const_2 = tf.constant(value=[[3.0, 4.0]],
                     dtype=tf.float32,
                     shape=(1, 2),
                     name='const_1',
                     verify_shape=True)

In [9]:
session = tf.Session()
print(session.run(fetches=[const_1, const_2]))

[array([[1., 2.]], dtype=float32), array([[3., 4.]], dtype=float32)]


In [15]:
#Variable Nodes
#When and how to use them
#Compare to constant nodes

var_1 = tf.Variable(initial_value=[1.0],
                    trainable=True,
                    collections=None,
                    validate_shape=True,
                    caching_device=None,
                    name='var_1',
                    variable_def=None,
                    dtype=tf.float32,
                    expected_shape=(1, None),
                    import_scope=None)

print(var_1)
init = tf.global_variables_initializer()
session.run(init)
print(session.run(fetches=var_1))

var_2 = var_1.assign(value=[2.0])
print(session.run(fetches=var_1))
print(session.run(fetches=var_2))

<tf.Variable 'var_1_4:0' shape=(1,) dtype=float32_ref>
[1.]
[1.]
[2.]


In [18]:
#Placeholder nodes
#When and how to use them
#Compare to constant and variable nodes

placeholder_1 = tf.placeholder(dtype=tf.float32,
                               shape=(1, 4),
                               name='placeholder_1')

print(placeholder_1)
print(session.run(fetches=placeholder_1, feed_dict={placeholder_1: [[1.0, 2.0, 3.0, 4.0]]}))

placeholder_2 = tf.placeholder(dtype=tf.float32,
                               shape=(2, 2),
                               name='placeholder_2')

print(placeholder_2)
print(session.run(fetches=[placeholder_1, placeholder_2], 
                  feed_dict={placeholder_1: [[1.0, 2.0, 3.0, 4.0]], placeholder_2: [[1.0, 2.0], [3.0, 4.0]]}))

Tensor("placeholder_1_1:0", shape=(1, 4), dtype=float32)
[[1. 2. 3. 4.]]
Tensor("placeholder_2_1:0", shape=(2, 2), dtype=float32)
[array([[1., 2., 3., 4.]], dtype=float32), array([[1., 2.],
       [3., 4.]], dtype=float32)]


In [23]:
#Operational nodes
#How to perfrom operations on existing nodes
#Build a mini computational graph

const_1 = tf.constant(value=[1.0])
const_2 = tf.constant(value=[2.0])
placeholder_1 = tf.placeholder(dtype=tf.float32)
#results = const_1 + const_2
results = tf.add(x=placeholder_1, y=const_2, name='results')

# y = Wx + b
W = tf.constant(value=[2.0])
b = tf.constant(value=[1.0])
x = tf.placeholder(dtype=tf.float32)
#y = W * x + b
mult = tf.multiply(x=W, y=x)
y = tf.add(x=mult, y=b)


#print(session.run(fetches=results, feed_dict={placeholder_1: [2.0]}))
print(session.run(fetches=y, feed_dict={x: [2.0, 3.0, 4.0]}))

[5. 7. 9.]


In [25]:
#Loss function and optimizers
#Training and Testing

# x_train = [1.0, 2.0, 3.0, 4.0]
# y_train = [2.0, 3.0, 4.0, 5.0]
# y_actual = [1.5, 2.5, 3.5, 4.5]
# loss = tf.reduce_sum(input_tensor=tf.square(x=y_train - y_actual))
# optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.05)
# train_step = optimizer.minimize(loss=loss)

# Linear Regression

In [26]:
# y = Wx + b

x_train = [1.0, 2.0, 3.0, 4.0]
y_train = [-1.0, -2.0, -3.0, -4.0]

W = tf.Variable(initial_value=[1.0], dtype=tf.float32)
b = tf.Variable(initial_value=[1.0], dtype=tf.float32)

x = tf.placeholder(dtype=tf.float32)
y_input = tf.placeholder(dtype=tf.float32)


y_output = W * x + b

loss = tf.reduce_sum(input_tensor=tf.square(x=y_output - y_input))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_step = optimizer.minimize(loss=loss)

session = tf.Session()
session.run(tf.global_variables_initializer())

print(session.run(fetches=loss, feed_dict={x: x_train, y_input: y_train}))

for _ in range(1000):
    session.run(fetches=train_step, feed_dict={x: x_train, y_input: y_train})
    
print(session.run(fetches=[loss, W, b], feed_dict={x: x_train, y_input: y_train}))

print(session.run(fetches=y_output, feed_dict={x: [5.0, 10.0, 15.0]}))

Instructions for updating:
Use tf.cast instead.
164.0
[3.1441516e-12, array([-1.0000007], dtype=float32), array([2.0641437e-06], dtype=float32)]
[ -5.000002 -10.000006 -15.000009]
